# Generated by Django 5.2.7 on 2025-10-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_of_courtesy', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('hire_date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('home_phone', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('notes', models.TextField()),
                ('reports_to', models.IntegerField()),
                ('phone_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('required_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField()),
                ('ship_via', models.IntegerField()),
                ('freight', models.IntegerField()),
                ('ship_name', models.CharField(max_length=200)),
                ('ship_address', models.CharField(max_length=200)),
                ('ship_city', models.CharField(max_length=200)),
                ('ship_region', models.CharField(max_length=200)),
                ('ship_postal_code', models.CharField(max_length=200)),
                ('ship_country', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity_per_unit', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('discontinued', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
