# Generated by Django 5.2.7 on 2025-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_birth_date_alter_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/d'),
        ),
    ]
